//Alex Lundin
//AML140830@utdallas.edu
//SE 3377.501 - CC++ in  UNIX
#ifndef PROGRAM4_H
#define  PROGRAM4_H
//typedef enum {NAMETOKEN=1 ,IDENTIFIERTOKEN ,NAME_INITIAL_TOKEN ,ROMANTOKEN ,SRTOKEN ,JRTOKEN ,EOLTOKEN ,INTTOKEN ,COMMATOKEN ,DASHTOKEN ,HASHTOKEN} tokens_t;
#endif // PROGRAM4_H

